=== noodle1983/pythontest/config/configuration.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT configure (config*)>
<!ATTLIST configure
	namespace CDATA #REQUIRED
>

<!ELEMENT config (name, desc, valuedef)>
<!ATTLIST config
	type CDATA #REQUIRED
>

<!ELEMENT name (#PCDATA)>

<!ELEMENT desc (#PCDATA)>

<!ELEMENT valuedef (ref?, default?, range?, enum?)>

<!ELEMENT ref (#PCDATA)>

<!ELEMENT default (#PCDATA)>

<!ELEMENT range (#PCDATA)>
<!ATTLIST range
	min CDATA #REQUIRED
>
<!ATTLIST range
	max CDATA #REQUIRED
>

<!ELEMENT enum (enumitem)>
<!ELEMENT enumitem (#PCDATA)>
<!ATTLIST enumitem
	value CDATA #REQUIRED
>
<!ATTLIST enumitem
	desc CDATA #REQUIRED
>

=== noodle1983/pythontest/config/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configure SYSTEM "configuration.dtd">
<configure namespace="test">
<config type="int">
	<name>total len</name>
	<desc>total len</desc>
	<valuedef></valuedef>
</config>
<config type="enum">
	<name>commandId</name>
	<desc>command id</desc>
	<valuedef>
	<enum>
		<enumitem value="0x01" desc="msg1"></enumitem>
	</enum>
	</valuedef>
</config>

</configure>
